---
- hosts: jenkins
  become: true
  vars:
    jenkins_url: http://localhost:8080
    jenkins_username: admin
    jenkins_password: admin
    nexus_username: admin
    nexus_password: admin
    add_credentials:  |
      import com.cloudbees.plugins.credentials.*
      import com.cloudbees.plugins.credentials.domains.Domain
      import com.cloudbees.jenkins.plugins.sshcredentials.impl.*
      import com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl
      import hudson.util.Secret
      import jenkins.model.*
      import hudson.security.*
      domain = Domain.global()
      store = Jenkins.instance.getExtensionList('com.cloudbees.plugins.credentials.SystemCredentialsProvider')[0].getStore()

      GITHUB_USER = new UsernamePasswordCredentialsImpl(CredentialsScope.GLOBAL,"Nexus", "Nexus Credentials","{{ nexus_username }}","{{ nexus_password }}")
      store.addCredentials(domain, GITHUB_USER)
      
  tasks:
  - name: Creating Nexus Credentials
    jenkins_script:
      script: "{{ add_credentials }}"
      url: "{{ jenkins_url }}"
      user: "{{ jenkins_username }}"
      password: "{{ jenkins_password }}"
    
