---
- hosts: jenkins1
  become: true
  vars:
    url: http://localhost:8080
    user: admin
    pwd: admin
    nexus_user: admin
    nexus_pwd: admin123
    nexus_id: Nexus
  tasks:
  - name: Creating Nexus Credentials
    uri:
      url: 'http://localhost:8080/credentials/store/system/domain/_/createCredentials'
      method: POST
      user: "{{ user }}"
      password: "{{ pwd }}"
      force_basic_auth: yes
      status_code: 302,200
      body: |
        json={
          "":"0",
          "credentials":{
          "scope":"global",
          "id":"{{ nexus_id }}",
          "username":"{{ nexus_user }}",
          "password":"{{ nexus_pwd }}",
          "description": "Nexus Credentials",
          "$class":
          "com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl"
          }
        }
    
