---
- hosts: new_jenkins
  become: true   
  tasks:
  - name: Create seed job
    vars:
      seed_name: seed
      
      seed_job: |
        pipelineJob('springboot-demo') {
          definition {
            cpsScm {
              scm {
                git('https://github.com/maheshwar807/springboot-demo.git'){node -> // is hudson.plugins.git.GitSCM
                    node / gitConfigName('maheshwar807')
                    node / gitConfigEmail('maheshwar.mannur@gmail.com')
                  branch('master')
                }
              }
              scriptPath('Jenkinsfile')
            }
          }
        }
    uri:
      url: "http://localhost:8080/createItem?name={{ seed_name }}"
      method: POST
      HEADER_Content-Type: application/xml
      body: "{{ seed_job }}"
    register: jenkins_seed_updated
    when: not seed_exists

  - name: Run seed job
    uri:
      url: "http://localhost:8080/job/{{ seed_name }}/build"
      method: POST
      status_code: 201
    when: jenkins_seed_updated|success
