---
- hosts: new_jenkins
  become: true   
  vars:
    jenkins_url: http://localhost:8080
    jenkins_username: admin
    jenkins_password: admin
  tasks:

  - name: Crumb Issuer
    vars:
      csrf_enable:  |
        import hudson.security.csrf.DefaultCrumbIssuer
        import jenkins.model.Jenkins

        if(!Jenkins.instance.isQuietingDown()) {
            def j = Jenkins.instance
            if(j.getCrumbIssuer() == null) {
                j.setCrumbIssuer(new DefaultCrumbIssuer(true))
                j.save()
                println 'CSRF Protection configuration has changed.  Enabled CSRF Protection.'
            }
            else {
                println 'Nothing changed.  CSRF Protection already configured.'
            }
        }
        else {
            println "Shutdown mode enabled.  Configure CSRF protection SKIPPED."
        }
    jenkins_script:
      script: "{{ csrf_enable }}"
      url: "{{ jenkins_url }}"
      user: "{{ jenkins_username }}"
      password: "{{ jenkins_password }}"

  - name: Create seed job
    vars:
      seed_name: seed
      seed_job: |
        pipelineJob('springboot-demo') {
          definition {
            cpsScm {
              scm {
                git('https://github.com/maheshwar807/springboot-demo.git'){node -> // is hudson.plugins.git.GitSCM
                    node / gitConfigName('maheshwar807')
                    node / gitConfigEmail('maheshwar.mannur@gmail.com')
                  branch('master')
                }
              }
              scriptPath('Jenkinsfile')
            }
          }
        }
    uri:
      url: "http://localhost:8080/createItem?name={{ seed_name }}"
      method: POST
      headers:
        Content-Type: application/xml
      body: "{{ seed_job }}"
    register: jenkins_seed_updated

  - name: Run seed job
    uri:
      url: "http://localhost:8080/job/{{ seed_name }}/build"
      method: POST
      status_code: 201
    when: jenkins_seed_updated|success
