---
- hosts: jenkins
  become: yes
  vars:
      jenkins_url: http://localhost:8080
      jenkins_username: admin
      jenkins_password: admin
      
  tasks:
    - name: Install Github Authentication Plugin
      jenkins_plugin:
        name: github-oauth
        url: "{{ jenkins_url }}"
        url_username: "{{ jenkins_username }}"
        url_password: "{{ jenkins_password }}"
        
    - name: Install Job DSL Plugin
      jenkins_plugin:
        name: job-dsl
        url: "{{ jenkins_url }}"
        url_username: "{{ jenkins_username }}"
        url_password: "{{ jenkins_password }}"
        
    - name: Install SonarQube Scanner Plugin
      jenkins_plugin:
        name: sonar
        url: "{{ jenkins_url }}"
        url_username: "{{ jenkins_username }}"
        url_password: "{{ jenkins_password }}"
        
    - name: Install Nexus Artifact Uploader Plugin
      jenkins_plugin:
        name: nexus-artifact-uploader
        url: "{{ jenkins_url }}"
        url_username: "{{ jenkins_username }}"
        url_password: "{{ jenkins_password }}"
    
    - name: Restart Jenkins
      service:
        name: jenkins
        state: restarted
