---
- hosts: new_jenkins
  become: true
  vars: 
    jenkins_url: http://localhost:8080
    jenkins_user: admin
    jenkins_password: admin
  tasks:
  - name: Download CLI jar
    get_url:
      url: http://localhost:8080/jnlpJars/jenkins-cli.jar
      dest: /opt/jenkins-cli.jar
      
  - name: Jenkins Initial Password
    shell: cat /var/lib/jenkins/secrets/initialAdminPassword
    changed_when: false
    register: init_password

  - name: New User
    shell: echo 'jenkins.model.Jenkins.instance.securityRealm.createAccount("{{ jenkins_user }}", "{{ jenkins_password }}")' | java -jar /opt/jenkins-cli.jar -s "{{ jenkins_url }}" -auth "{{ jenkins_user }}":"{{ init_password.stdout }}" -noKeyAuth groovy = – 
    
  - name: Skip Suggested Plugins Step
    vars:
      skip_plugins: |
        import static jenkins.model.Jenkins.instance as jenkins
        import jenkins.install.InstallState
        if (!jenkins.installState.isSetupComplete()) {
          println '--> Neutering SetupWizard'
          InstallState.INITIAL_SETUP_COMPLETED.initializeState()
        }
    jenkins_script:
      script: "{{ skip_plugins }}"
      url: "{{ jenkins_url }}"
      user: "{{ jenkins_user }}"
      password: "{{ jenkins_password }}"

  - name: Install Suggested Plugins
    shell: java -jar /opt/jenkins-cli.jar  -s "{{ jenkins_url }}" install-plugin cloudbees-folder timestamper pipeline-model-definition subversion ldap antisamy-markup-formatter ws-cleanup github-organization-folder ssh-slaves email-ext build-timeout ant pipeline-stage-view matrix-auth mailer credentials-binding gradle git pam-auth github-oauth job-dsl sonar nexus-artifact-uploader

  - name: Pause for Plugins to Install
    pause:
      minutes: 5

  - name: Restart Jenkins
    service:
      name: jenkins
      state: restarted
