---
- hosts: new_jenkins
  become: true
  vars:
    jenkins_url: http://localhost:8080
    jenkins_username: admin
    jenkins_password: admin
    approve_script: |
      import javaposse.jobdsl.plugin.GlobalJobDslSecurityConfiguration
      import jenkins.model.GlobalConfiguration

      // Disable Job DSL script approval
      GlobalConfiguration.all().get(GlobalJobDslSecurityConfiguration.class).useScriptSecurity=false
      GlobalConfiguration.all().get(GlobalJobDslSecurityConfiguration.class).save()

  tasks:
  - name: Disable Script Security
    jenkins_script:
      script: "{{ approve_script }}"
      url: "{{ jenkins_url }}"
      user: "{{ jenkins_username }}"
      password: "{{ jenkins_password }}"
