---
- hosts: new_jenkins
  become: true
  vars:
    jenkins_url: http://localhost:8080
    jenkins_username: admin
    jenkins_password: admin
    approve_script: |
      import javaposse.jobdsl.plugin.GlobalJobDslSecurityConfiguration
      import jenkins.model.GlobalConfiguration
      import org.kohsuke.stapler.StaplerRequest

      // current value  
      println GlobalConfiguration.all().get(GlobalJobDslSecurityConfiguration.class).useScriptSecurity

      // change vaue
      StaplerRequest stapler = null
      net.sf.json.JSONObject jsonObject = new net.sf.json.JSONObject()
      //jsonObject.put("useScriptSecurity", false)  // it uses has method https://github.com/jenkinsci/job-dsl-plugin/blob/6a70bba91e671ebe72fd682e92e9abea48a2b050/job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/GlobalJobDslSecurityConfiguration.groovy#L21
      GlobalConfiguration.all().get(GlobalJobDslSecurityConfiguration.class).configure(stapler, jsonObject)

      // new value
      println GlobalConfiguration.all().get(GlobalJobDslSecurityConfiguration.class).useScriptSecurity
    
    jenkins_script:
      script: "{{ approve_script }}"
      url: "{{ jenkins_url }}"
      user: "{{ jenkins_username }}"
      password: "{{ jenkins_password }}"
