---
- hosts: new_jenkins
  become: true
  vars:
    jenkins_url: http://localhost:8080
    jenkins_username: admin
    jenkins_password: admin
    approve_script: |
      import jenkins.model.Jenkins
      Jenkins j = Jenkins.instance

      if(!j.isQuietingDown()) {
          def job_dsl_security = j.getExtensionList('javaposse.jobdsl.plugin.GlobalJobDslSecurityConfiguration')[0]
          if(job_dsl_security.useScriptSecurity) {
              job_dsl_security.useScriptSecurity = false
              println 'Job DSL script security has changed.  It is now disabled.'
              job_dsl_security.save()
              j.save()
          }
          else {
              println 'Nothing changed.  Job DSL script security already disabled.'
          }
      }
      else {
          println 'Shutdown mode enabled.  Configure Job DSL script security SKIPPED.'
      }
    
    jenkins_script:
      script: "{{ approve_script }}"
      url: "{{ jenkins_url }}"
      user: "{{ jenkins_username }}"
      password: "{{ jenkins_password }}"
